### ISSUE TITLE
cannot send services to statsd_host:8126:  [Errno -3] Try again

### ISSUE THREAD

**Issue by BouchaaraAdil** [DataDog/dd-trace-py#512]
actually w're getting  and monitoring Django app APMs by setting those traces related spans and services are reported correctly,
-from time to time we're are getting 
`cannot send services to agent_host:8126: ''`
`cannot send services to agent_host:8126: [Errno -3] Try again`
`cannot send spans to agent_hostl:8126: [Errno 104] Connection reset by peer`

 not sure if anything is missed
datadog settings:
```
# Datadog
DATADOG_TRACE = {
    'DEFAULT_SERVICE': os.environ.get('DATADOG_APP_NAME'),
    'TAGS': {'env': os.environ.get('DATADOG_APP_ENV')},
    'AGENT_HOSTNAME': os.environ.get('DATADOG_TRACE_AGENT_HOSTNAME'),
    'AGENT_PORT': os.environ.get('DD_AGENT_PORT'),
    'ENABLED': True
}

dd_statsd_options = {
    'statsd_host': os.environ.get('DATADOG_TRACE_AGENT_HOSTNAME'),
    'statsd_port': 8125
}

initialize(statsd_use_default_route=True, **dd_statsd_options)
```
one thing if i can control sending spans, services to the agent,  send them every three 3 seconds of five

**Comment by palazzem** [comment]
Hello @BouchaaraAdil ! your configuration seems correct, especially if you can send traces and statsd metrics from time to time. Can you please send us a flare from your agent as described here https://docs.datadoghq.com/agent/troubleshooting/#send-a-flare?

It will open a support ticket that will include your Agent logs (nothing will be made public). Also if you can provide more details about:
* what version of the Agent and `dd-trace-py` are you using?
* on what environment is your Django application running? Multiple nodes, Kubernetes, Docker, etc..
* is the Agent always reachable from your Django application?
* do you see any drop from reported statsd metrics?
* do you see any other error in your application logs (or Agent logs)

Consider that sending the flare is still useful because it will help us with the triage. Thanks for reporting your feedback!

**Comment by BouchaaraAdil** [comment]
sure, Thank You @palazzem 
- version of the Agent: 6.3.0
- `dd-trace-py`: `0.12.0`
- environment: Multiple nodes, Kubernetes
- Agent always reachable from your Django
- logs erros from agent:
`There was an error querying the ntp host: read udp ip:38942->ip:123: i/o timeout`
`ERROR (receiver.go:275) - cannot decode v0.3 services payload: msgp: attempted to decode type "nil" with method for "str"`
`ERROR (agent.go:215) - skipping trace with root too far in past, root`

**Comment by palazzem** [comment]
Thanks for the follow-up! Checking the logs, I have few more questions:
* what integrations are you using? only Django or do you use something else? (i.e. `requests` or some driver connectors via the `patch_all()`/`patch()`)
* `dd-trace-py` 0.12.1 has an unfortunate regression on Celery. If you're not using Celery, can you try the latest version? We fixed some services payload that were reported as wrong in 0.12.0. It should address the `cannot decode v0.3 services payload` error. If you update and you still see this error, the list of activated integrations will help us to detect what is wrong with the service reporting.
* it seems the `ntp` synchronization doesn't work as expected. Can you double check if the clock in the Agent pods is correct? if not, adjusting the clock should fix the `skipping trace with root too far in past`

Thanks!

**Comment by BouchaaraAdil** [comment]
what integrations are you using?
i think it could be related to `requests` package used in dd-trace-py to send spans to the agent
```
DEBUG [/usr/local/lib/python2.7/site-packages/ddtrace/monkey.py:102] - failed to patch aiopg: module not installed
DEBUG [/usr/local/lib/python2.7/site-packages/ddtrace/monkey.py:102] - failed to patch pymysql: module not installed
DEBUG [/usr/local/lib/python2.7/site-packages/ddtrace/monkey.py:119] - already patched: ddtrace.contrib.mysqldb
DEBUG [/usr/local/lib/python2.7/site-packages/ddtrace/monkey.py:102] - failed to patch mysql: module not installed
DEBUG [/usr/local/lib/python2.7/site-packages/ddtrace/monkey.py:102] - failed to patch botocore: module not installed
DEBUG [/usr/local/lib/python2.7/site-packages/ddtrace/monkey.py:102] - failed to patch cassandra: module not installed
DEBUG [/usr/local/lib/python2.7/site-packages/ddtrace/monkey.py:119] - already patched: ddtrace.contrib.redis
DEBUG [/usr/local/lib/python2.7/site-packages/ddtrace/monkey.py:119] - already patched: ddtrace.contrib.celery
DEBUG [/usr/local/lib/python2.7/site-packages/ddtrace/monkey.py:119] - already patched: ddtrace.contrib.sqlite3
DEBUG [/usr/local/lib/python2.7/site-packages/ddtrace/monkey.py:102] - failed to patch pylibmc: module not installed
DEBUG [/usr/local/lib/python2.7/site-packages/ddtrace/monkey.py:102] - failed to patch pymongo: module not installed
DEBUG [/usr/local/lib/python2.7/site-packages/ddtrace/monkey.py:102] - failed to patch aiohttp: module not installed
DEBUG [/usr/local/lib/python2.7/site-packages/ddtrace/monkey.py:102] - failed to patch mongoengine: module not installed
DEBUG [/usr/local/lib/python2.7/site-packages/ddtrace/monkey.py:119] - already patched: ddtrace.contrib.psycopg
DEBUG [/usr/local/lib/python2.7/site-packages/ddtrace/monkey.py:102] - failed to patch boto: module not installed
DEBUG [/usr/local/lib/python2.7/site-packages/ddtrace/monkey.py:119] - already patched: ddtrace.contrib.elasticsearch
INFO [/usr/local/lib/python2.7/site-packages/ddtrace/monkey.py:89] - patched 0/16 modules (celery,elasticsearch,mysqldb,psycopg,redis,sqlite3)
```
- i will upgrade tracing package to `0.12.1`
About:
- Can you double check if the clock in the Agent pods is correct?
not sure i understand, can you elaborate more please?

**Comment by palazzem** [comment]
Yes probably the 0.12.1 version should address the services issue. I see that you're using `celery` and we're fixing a regression reported here: https://github.com/DataDog/dd-trace-py/issues/495

About the Agent clock, I'm wondering if the internal clock is properly in sync with the rest of the system. From the log, it seems that the pod that is sending the trace has a different clock than the one used in the Agent. If not, are you sending long traces (for instance) from a long running background job?

**Comment by palazzem** [comment]
OK, let's be sure other problems are addressed, then we can go back to the the long running job monitoring.

**Comment by BouchaaraAdil** [comment]
i contacted our backend team, they have been already upgraded to ddtrace 0.12.1 and got issues with it as referenced here https://github.com/DataDog/dd-trace-py/issues/495#ref-pullrequest-338915306.
is there any other option please.

**Comment by BouchaaraAdil** [comment]
`cannot decode v0.3 services payload` is not persisting
but this one still on the agent logs `ERROR (agent.go:215) - skipping trace with root too far in past`
also this one when datadog logs  enabled `[ AGENT ] 2018-07-18 15:27:17 UTC | WARN | (docker.go:197 in forwardMessages) | Can't parse docker message: expected a whitespace after header`

**Comment by palazzem** [comment]
OK, so:
* for `skipping trace with root too far in past` we can work on it once we have Celery working properly on your system (I'll ask you to test a custom branch once it's ready if you can)
* for `Can't parse docker message` I think it's better if you contact directly our support because it's handled not by the APM team. This will be way faster. On the other hand, we can handle other 2 problems (skipping trace and the regression of Celery) in this thread.

Thanks a lot!

**Comment by BouchaaraAdil** [comment]
Hey @palazzem 
Thanks a lot for your collaboration
we upgraded the agent to the latest one `6.3.3`
and we still getting those errors
```
cannot send services to agent_host:8126: ' '
cannot send services to agent_host:8126: [Errno -3] Try again
cannot send spans to agent_hostl:8126: [Errno 110] Operation timed out']
```

**Comment by palazzem** [comment]
Thank you very much! I'm going to investigate and see if these integrations are sending wrongly `services` metadata, that will be removed since newer versions of the Agent can auto-detect that. I will check these integrations that are listed in your log as enabled: celery, elasticsearch, mysqldb, psycopg, redis, sqlite3.

Will reach you back very soon.

**Comment by palazzem** [comment]
Also, can you double check the third line? maybe there is a copy-paste error, but do you confirm that `agent_hostl:8126` is in real `agent_host` and not `agent_hostl`? Thanks!

**Comment by BouchaaraAdil** [comment]
yes sorry i made a typo, `agent_host` is a kubernetes service for ddg agent

**Comment by BouchaaraAdil** [comment]
@palazzem is there any option to increase `timeout` when submitting spans, services to the agent ?
or could you please work on that.

**Comment by palazzem** [comment]
Sure, it's in our backlog but we need first to stabilize one of our Integrations (Celery). As soon it's done, we'll work also on this specific issue. Thanks for your patience!

**Comment by eedwards-sk** [comment]
> cannot send spans to `{host}`:8126: [Errno 104] Connection reset by peer

getting this regularly on 0.17.1

**Comment by mrmachine** [comment]
Getting `cannot send spans to datadog:8126: [Errno -2] Name or service not known` with some regularity. Running Django project with celery under Docker Compose on a single host. Datadog agent is run via Docker Compose also. These errors are showing up in Sentry as originating from the celery service.

I wonder if these exceptions are also occurring in our gunicorn service, and I wonder if these exceptions are having any impact on the requests/tasks being instrumented? If Datadog agent is crashing out of requests/tasks because it is unable to send a trace (for any reason), that's bad. I would hope that Datadog agent will still allow the instrumented request/task to complete even if it is unable to send its trace data?

**Comment by mrmachine** [comment]
Also seeing ```
failed_to_send traces to Datadog Agent: HTTP error status 413, reason Request Entity Too Large, message Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Wed, 20 Feb 2019 22:33:42 GMT
Content-Length: 18
```
in Sentry, originating from our celery service.

**Comment by brettlangdon** [comment]
I am going to close this card for now since it seems the original issue has been resolved, but it appears there are a few other semi-related issues being tracked here.

@mrmachine and @eedwards-sk if you are still experiencing issues would you be willing to open new issues so we can keep better track of them?
