### ISSUE TITLE
Issue in ddtrace.profiling.collector.stack:StackCollector when uing greenlet

### ISSUE THREAD

**Issue by SadmiB** [DataDog/dd-trace-py#5540]
### Summary of the problem

StackCollector fails with the error below:

```
Exception in thread ddtrace.profiling.collector.stack:StackCollector:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/site-packages/ddtrace/internal/periodic.py", line 56, in run
    self._target()
  File "/usr/local/lib/python3.8/site-packages/ddtrace/profiling/collector/__init__.py", line 42, in periodic
    for events in self.collect():
  File "ddtrace/profiling/collector/stack.pyx", line 478, in ddtrace.profiling.collector.stack.StackCollector.collect
  File "ddtrace/profiling/collector/stack.pyx", line 314, in ddtrace.profiling.collector.stack.stack_collect
  File "ddtrace/profiling/collector/_task.pyx", line 104, in ddtrace.profiling.collector._task.list_tasks
  File "ddtrace/profiling/collector/_task.pyx", line 122, in ddtrace.profiling.collector._task.list_tasks
  File "/usr/local/lib/python3.8/weakref.py", line 208, in items
    for k, wr in self.data.items():
RuntimeError: dictionary changed size during iteration
```
### Which version of dd-trace-py are you using?
`ddtrace==1.9.3`
### Which version of pip are you using?
pip `18.1-5`
python `3.8`
### Which libraries and their versions are you using?
```
alabaster==0.7.13
alembic==1.4.2
amqp==2.5.2
atomicwrites==1.4.0
attrs==20.1.0
Babel==2.12.1
billiard==3.6.3.0
black==22.1.0
blinker==1.4
blueprint==3.4.2
boto3==1.18.7
botocore==1.21.65
celery==4.4.2
celery-once==3.0.1
celery-redbeat==0.13.0
certifi==2020.4.5.1
cffi==1.15.1
cfgv==3.3.1
chardet==3.0.4
click==8.0.0
coverage==5.1
cryptography==39.0.2
csession==0.1.4
distlib==0.3.6
dnspython==2.3.0
docker==5.0.3
docutils==0.19
email-validator==1.1.3
expiringdict==1.2.2
filelock==3.10.0
flake8==4.0.1
Flask==1.1.2
Flask-Cors==3.0.9
Flask-HTTPAuth==4.1.0
Flask-Migrate==2.5.3
flask-redis==0.4.0
Flask-SQLAlchemy==2.4.4
freezegun==0.3.15
gunicorn==20.1.0
identify==2.5.21
idna==2.9
imagesize==1.2.0
importlib-metadata==1.6.0
iniconfig==2.0.0
iso3166==1.0.1
isort==5.10.1
itsdangerous==1.1.0
Jinja2==2.11.2
jmespath==0.10.0
jsonify==0.5
kombu==4.6.8
launchdarkly-server-sdk==7.5.1
Mako==1.1.3
MarkupSafe==1.1.1
mccabe==0.6.1
more-itertools==8.3.0
moto==2.2.0
mypy-extensions==1.0.0
nodeenv==1.7.0
numpy==1.24.2
packaging==20.4
pandas==1.2.1
pathspec==0.11.1
platformdirs==3.1.1
pluggy==0.13.1
pre-commit==2.16.0
psycopg2==2.8.6
psycopg2-binary==2.8.6
py==1.9.0
pycodestyle==2.8.0
pycparser==2.21
pydantic==1.7.3
pyflakes==2.4.0
Pygments==2.14.0
PyJWT==1.7.1
pyparsing==2.4.7
pyRFC3339==1.1
pytest==6.0.1
pytest-cov==2.9.0
pytest-mock==3.3.1
python-dateutil==2.8.1
python-dotenv==0.15.0
python-editor==1.0.4
python-json-logger==0.1.11
pytz==2020.1
PyYAML==6.0
redis==3.5.3
regex==2020.7.14
requests==2.24.0
requests-mock==1.8.0
responses==0.13.1
s3transfer==0.5.2
semver==2.13.0
simplejson==3.17.0
six==1.15.0
snowballstemmer==2.2.0
Sphinx==3.2.1
sphinx-rtd-theme==0.5.0
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-httpdomain==1.7.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
SQLAlchemy==1.3.19
tenacity==8.2.2
toml==0.10.2
tomli==2.0.1
tonyg-rfc3339==0.1
urllib3==1.25.10
vine==1.3.0
virtualenv==20.21.0
wcwidth==0.2.3
websocket-client==1.5.1
Werkzeug==1.0.1
xmltodict==0.13.0
zipp==3.1.0
gevent==22.10.2
greenlet==2.0.2
psycogreen==1.0.2
ddtrace==1.9.3
```

**Comment by P403n1x87** [comment]
This should be fixed as a by-product of #5338. We will backport it to 1.9.

**Comment by SadmiB** [comment]
@P403n1x87 Thanks for the update, in which exact version will this be included? or in all 1.9;* versions

**Comment by P403n1x87** [comment]
@SadmiB the next 1.9 release with the fix should be 1.9.6

**Comment by SadmiB** [comment]
I upgraded out ddtrace to `1.9.6` but the issue still occurring in my case

![image](https://github.com/DataDog/dd-trace-py/assets/26244234/8ca26506-da8c-4bec-b648-a8f1e1120028)

**Comment by P403n1x87** [comment]
@SadmiB thanks for the extra feedback. I'm wondering whether this is just an instance of https://github.com/python/cpython/issues/79796, since the problem seems to originate from within `weakref.py` itself. Could you confirm that you are on the latest patch release for 3.8? If so, would you be able to upgrade to a newer minor release of Python and see if the problem still occurs?

**Comment by SadmiB** [comment]
Thanks for your response, yes it looks like `weakref.py` is related, we are using the latest version of python `3.8.16`
