### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by qiao-meng-zefr** [DataDog/dd-trace-py#680]
datadog==0.23.0
ddtrace==0.15.0
Pympler==0.6

I have a simple script here that overtime you can see the ddtrace.span.Span class's number of objects and total size of memory is increasing.

I've also tried this script inside a `python:3.6-slim` container that can reproduce the result.

```
import datadog
import ddtrace
from ddtrace import tracer
from pympler import muppy, summary, asizeof

datadog.initialize(
        statsd_host="172.17.0.1",
        statsd_port=8125,
    )

@tracer.wrap()
def publish():
    return 1

for i in range(10 ** 6):
    publish()
    if i % 1000 == 0:
        all_objs = muppy.get_objects()
        print(f"MEMORY PROFILER object gauge. {len(all_objs)}")
        summary.print_(summary.summarize(all_objs))
```

Thank you for the help!

**Comment by Kyle-Verhoog** [comment]
Hi @qiao-meng-zefr!

Thanks for the detailed report.

My suspicion is that for the example you provide there are more spans being created than are being flushed. If you were to add a `time.sleep()` where you print the usage statistics then my guess would be that you wouldn't see the memory use growing.

Let me know if this is indeed the case for you 😄.

**Comment by Kyle-Verhoog** [comment]
For reference here is the logic for flushing traces to the writer. See on line 170 that it sleeps for a second between flushes: https://github.com/DataDog/dd-trace-py/blob/7db12f1c398c07cd5baf91c571aed672dbb6496d/ddtrace/writer.py#L133-L170

**Comment by qiao-meng-zefr** [comment]
Hi Kyle,

I tried with putting a sleep before the print. But still able to see the memory growing.

Here is my updated script:
```python
import os
import ddtrace
import time
from ddtrace import tracer
from pympler import muppy, summary, asizeof

@tracer.wrap()
def publish():
    return 1

for i in range(10 ** 6):
    publish()
    if i % 1000 == 0:
        time.sleep(5)
        all_objs = muppy.get_objects()
        print(f"MEMORY PROFILER object gauge. {len(all_objs)}")
        summary.print_(summary.summarize(all_objs))
```

Thank you for taking a look!

**Comment by Kyle-Verhoog** [comment]
Hmm interesting.

I am able replicate even with long sleep delays. We'll investigate this further.

Thanks for the report!

**Comment by brettlangdon** [comment]
@qiao-meng-zefr sorry for the long delay getting back to you here.

@Kyle-Verhoog and I were able to do some more memory testing via Python's [tracemalloc](https://docs.python.org/3/library/tracemalloc.html) along with using `top` to monitor the process and we believe this isn't actually an issue. We were able to run the same program as you generating a million spans in a very short period of time and we did not see memory usage bloat for the application.


```python
import linecache
import os
import tracemalloc

from ddtrace import tracer


def display_top(snapshot, key_type='lineno', limit=4):
    snapshot = snapshot.filter_traces((
        tracemalloc.Filter(False, '<frozen importlib._bootstrap>'),
        tracemalloc.Filter(False, '<unknown>'),
    ))
    top_stats = snapshot.statistics(key_type)

    print('Top %s lines' % limit)
    for index, stat in enumerate(top_stats[:limit], 1):
        frame = stat.traceback[0]
        # replace '/path/to/module/file.py' with 'module/file.py'
        filename = os.sep.join(frame.filename.split(os.sep)[-2:])
        print('#%s: %s:%s: %.1f KiB'
              % (index, filename, frame.lineno, stat.size / 1024))
        line = linecache.getline(frame.filename, frame.lineno).strip()
        if line:
            print('    %s' % line)

    other = top_stats[limit:]
    if other:
        size = sum(stat.size for stat in other)
        print('%s other: %.1f KiB' % (len(other), size / 1024))
    total = sum(stat.size for stat in top_stats)
    print('Total allocated size: %.1f KiB' % (total / 1024))


@tracer.wrap()
def publish():
    return 1


tracemalloc.start()
for i in range(10 ** 6):
    publish()
    if i % 10000 == 0:
        snapshot = tracemalloc.take_snapshot()
        display_top(snapshot)

```

**Comment by brettlangdon** [comment]
@qiao-meng-zefr I am closing this for now, please feel free to open again if you need to.

**Comment by klette** [comment]
We're seeing explosive growth in memory usage as well, so their might be something going on here.

Setup:
Heroku
python 3.6.6
django==2.0.8
ddtrace==0.18.0
datadog==0.26.0

Patching:
```
    ddtrace.patch(
        botocore=True,  # boto3
        celery=True,
        psycopg=True,
        redis=True,
        requests=True,
    )
```

The following graph shows two runs of a quite intensive batch job:
![screenshot_2018-12-17 metrics heroku](https://user-images.githubusercontent.com/88143/50112996-031ef100-0241-11e9-8d5e-c3a396534301.png)

The rapid climb (and kill) is with `DD_TRACE_ENABLED=true`, the period after is with `DD_TRACE_ENABLED=false` - so quite clear what causes the memory issues.

We are seing quite a lot of `ddtrace.writer` errors, so I have a hunch that something goes haywire once the span writing gets backed up.

**Comment by brettlangdon** [comment]
@klette thank you for reaching out and sharing this information.

Something that we released recently was adding tracing support for `dbapi2` `fetchall`/`fetchmany`/`fetchone`.

One of the things we noticed is that libraries like `psycopg2` will default to using `fetchone()` during loops so if you have something like `for row in cursor:` and the result set happens to be 100k, then we create 100k spans, which will definitely bloat the memory a bit, have a performance impact, and traces will get rejected by the agent because they are too large.

If this sounds like it could be the cause of your issue, we are working on a fix for this to be released soon. If you wanted a change in the meantime to alleviate the issue you can do `for row in cursor.fetchall()` for now. 

I am sorry that this issue had an impact on your system that meant you needed to disable tracing. Please let me know if the above does not sound like the issue you could be seeing and I would be continue to diagnose with you.

**Comment by brettlangdon** [comment]
@klette version `0.19.0` has been released which disables the tracing of `fetchone`/`fetchmany`/`fetchall` by default which may address this issue that you saw.

Please let me know if you continue to have issues!!!

**Comment by klette** [comment]
@brettlangdon Awesome, I'll test the new release next week and let you know if it solves our issue :-)

**Comment by qiao-meng-zefr** [comment]
Just want to report that I'm still experiencing this issue with `ddtrace==0.21.0`. Sorry for such a long pause because I didn't get the chance to look into this.

tracemalloc doesn't show ddtrace as the cause for some reason. But after I disable tracer.wrap in my app the memory grow did stop. So I'm still suspicious about ddtrace. Sorry!

I did a little digging, and found that in `Tracer.trace` the span is added to the context ([link here](https://github.com/DataDog/dd-trace-py/blob/v0.21.0/ddtrace/tracer.py#L240)). And this context is the tracer's context. So if I'm using [ddtrace.tracer](https://github.com/DataDog/dd-trace-py/blob/v0.21.0/ddtrace/__init__.py#L10), does it mean the span will be added to this global tracer's context and never removed (because the span is still referred in context hence its `__exit__` will never be called)?

Just poking around. I could totally be wrong. Thanks for the help!

**Comment by qiao-meng-zefr** [comment]
I've added a track of `len(ddtrace.tracer.get_call_context()._trace)` in my app and I can actually see it grows to hundreds of thousands quickly.

I realize that in `context.add_span` the span is added to self._trace, but in `context.close_span` it was not removed from self._trace.

Could this be an easy change by pop out that span from the list?

**Comment by brettlangdon** [comment]
@qiao-meng-zefr how are you using `Tracer.trace`?

We always recommend creating a span with a `with` statement to ensure it is always closed.

```python
from ddtrace import tracer

with tracer.trace('span.name'):
    pass
```

Otherwise you will always have to ensure that `span.finish()` is called:

```python
from ddtrace import tracer

span = tracer.trace('span.name')

# Do something cool here

span.finish()
```

If `span.finish()` is never called, then it is never removed from the context and yes it could continue to grow on forever in size.

**Comment by qiao-meng-zefr** [comment]
@brettlangdon I decorate `tracer.wrap` on my function, following [this doc](http://pypi.datadoghq.com/trace/docs/basic_usage.html#decorator)
```python
from ddtrace import tracer

class Worker:

    @tracer.wrap()
    def run(self):
        print("working")
```

And I do configure in main before the worker runs.
```
ddtrace.tracer.configure(
    wrap_executor=custom_wrap_executor,  # my customized wrap executor
    hostname=settings.datadog_trace_agent_hostname
)
```

Is this correct?

**Comment by brettlangdon** [comment]
@qiao-meng-zefr how long does `Worker.run` run for? I assume this is a long running process that does a lot of work?

Each context represents a single trace that will group all of the spans created together under the root span (the first span/top level span/etc) until the root span completes. If the root span is never closed then the trace will never be flushed and will stay in memory forever.

This means your `@tracer.wrap()` will keep all spans created by/under `Worker.run` in memory until `Worker.run` has finished executing.

Normally this is fine and expected, but if `Worker.run` is creating hundreds of thousands of other spans 1) that trace isn't going to be very usable anyways since that is way too many spans to be able to reliably view or debug 2) the trace would probably be too large to flush anyways (we have a 10mb size limit per payload to the trace agent) 3) as you have found, it uses a ton of memory.

It might be better to evaluate the spans created by `Worker.run` and determine which are necessary, you might be better of doing higher level groupings of spans, for example:

```python
# Instead of this
with tracer.trace('span.name'):
    for i in range(100000):
        with tracer.trace('subspan.name'):
            # do something


# Do this
with tracer.trace('span.name'):
    with tracer.trace('doing.some.work'):
        for i in range (1000000):
            # do something
```

Does this make sense? Helpful?

What are you using `wrap_executor` for? Mostly just curious, I haven't seen that many people use this configuration option much.

**Comment by qiao-meng-zefr** [comment]
@brettlangdon My `Worker.run` is a process that runs forever actually. That would explain it.

I have the root created even before `Worker.run`. After I move it inside my forever loop and the problem went away.

Thank you very much for the explanation.

**Comment by brettlangdon** [comment]
@qiao-meng-zefr ah, yeah, that'll do it!

Glad you were able to resolve the issue, please feel free to reach out again in the future if you have questions/issues.
