### ISSUE TITLE
ddtrace still attempts to send spans to localhost:8126 when disabled in Django

### ISSUE THREAD

**Issue by al-the-x** [DataDog/dd-trace-py#798]
Seems related to #304. The project is using `django==1.11.6` and `ddtrace==0.12.0` and has `DATADOG_TRACE` and `LOGGING` defined in `settings/test.py` as follows:

```python
DATADOG_TRACE = {
  'ENABLED': False
}
## . . . 
LOGGING.update({
    'disable_existing_loggers': True,
    'handlers': {
        'console': {
            'class': 'logging.NullHandler',
        }
    },
    'loggers': {
        'ddtrace': {
            'handlers': [ 'console' ],
            'level': 'ERROR',
        }
    }
})
```

However when running any test using `manage.py test --settings=settings.test`, which uses `django_nose.NoseTestSuiteRunner`, the following is logged to  the `ddtrace` logger:

```
ddtrace.writer: ERROR: cannot send spans to localhost:8126: [Errno 61] Connection refused
ddtrace.writer: ERROR: cannot send spans to localhost:8126: [Errno 61] Connection refused
ddtrace.writer: ERROR: cannot send spans to localhost:8126: [Errno 61] Connection refused
```

...apparently repeated for every span, as I can affect the number of log messages by [manually instrumenting a method](http://pypi.datadoghq.com/trace/docs/basic_usage.html#manual-instrumentation) exercised by the tests via [`ddtrace.Tracer.wrap`](http://pypi.datadoghq.com/trace/docs/advanced_usage.html#ddtrace.Tracer.wrap) et al.

I have demonstrated -- via additional logging -- that `settings.DATADOG_TRACE['ENABLED'] is False` inside the wrapped function. Why is `ddtrace` still trying to send spans to `localhost:84126`...?

**Comment by al-the-x** [comment]
I'll put together an isolated example with a trivial project that I can share in a gist and play around with the versions of Django and `ddtrace`. Is there something wrong with the configuration for this project? I just joined the team and am trying to clean up the weirdness that everyone else has learned to ignore.

**Comment by al-the-x** [comment]
Just from toying around with the app, I've found that I can up the `level` on the `ddtrace` logger to silence the errors, but that's just masking the problem, really (which is kind of what everyone was doing already). It _shouldn't_ be trying to send spans _at all_, AFAICT, correct?

**Comment by majorgreys** [comment]
@al-the-x, in our tests you'll find that instead of the `ddtrace.tracer` we make use of a "dummy" tracer:

https://github.com/DataDog/dd-trace-py/blob/master/tests/utils/tracer.py#L6

As an example, our `django` tests monkey patch the tracer writer for the `DummyWriter`:

https://github.com/DataDog/dd-trace-py/blob/master/tests/contrib/django/utils.py#L22

This avoids the situation where the tracer is writing spans out to the agent, which it expects by default to be running on `localhost:8126`.

We hope this addresses your question. If not, please don't hesitate to ask further questions or suggest how we can improve upon how the tracer can be used in scenarios like yours where it's enabled for tests.

**Comment by al-the-x** [comment]
Somewhat and thanks for the insight. What does [the `ENABLED` flag](http://pypi.datadoghq.com/trace/docs/web_integrations.html#django) actually control, if not the sending of spans? Shouldn't it prevent sending spans?

**Comment by kevinc** [comment]
just noticed this happening in my tests as well

@majorgreys so is your recommendation to make use of that dummy writer? i'd be curious about the answer to @al-the-x 's question as well

**Comment by paultiplady** [comment]
@majorgreys this looks like a bug, the docs state 

```
* ``ENABLED`` (default: ``not django_settings.DEBUG``): defines if the tracer is
  enabled or not. If set to false, the code is still instrumented but no spans
  are sent to the trace agent. This setting cannot be changed at runtime
  and a restart is required. By default the tracer is disabled when in ``DEBUG``
  mode, enabled otherwise.
```

But from this thread (and inspecting the code) it looks like this isn't actually wired up. 

Expected behaviour is that there is some way to turn off tracing when the module is enabled, so that I can run my code without errors in a dev environment.

Can you please clarify how we're supposed to turn off tracing in a live app, if there is a way to do it? Thanks!

**Comment by nickpresta** [comment]
Is there an update on this? Is the current workaround to disable logging to suppress the errors and just deal with the fact that spans are being sent to a non-existent agent?

**Comment by brettlangdon** [comment]
@nickpresta my apologies that we do not have an update here just yet.

However, if there is a bug with the Django `ENABLED` setting, this setting should be controlling `tracer.enabled`. You could do the following as a workaround.

```python
from ddtrace import tracer
tracer.enabled = False
```

This is where it is used to push traces into the writer: https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/tracer.py#L421-L436

I am not 100% sure here, but this _might_ need to happen after Django is configured since otherwise our Django integration might overwrite `tracer.enabled` and re-enable it.

**Comment by brettlangdon** [comment]
This is likely the place where the bug is: https://github.com/DataDog/dd-trace-py/blob/5f8594aff6e74470579608b1a2f57077522d9c2a/ddtrace/contrib/django/conf.py#L113-L121

**Comment by al-the-x** [comment]
Also suspicious:
https://github.com/DataDog/dd-trace-py/blob/5f8594aff6e74470579608b1a2f57077522d9c2a/ddtrace/contrib/django/apps.py#L35

Combined with above, the `ENABLED` setting is not lazily evaluated and may be cached on the `tracer` or `DatadogSettings.user_settings` or reset to the default after a successful test run, since `DEBUG is False` while tests are running.

**Comment by al-the-x** [comment]
Now at a NEW day job, I'm experiencing the same problem in a Heroku dyno that I have explicitly set `DATADOG_TRACE_DISABLED=true`:

```
{"event": "failed to send traces to Datadog Agent at http://localhost:8126", "exc_info": ["<class 'ConnectionRefusedError'>", "ConnectionRefusedError(111, 'Connection refused')", "<traceback object at 0x7f0b6a9f3340>"]}
```

Since it's a one-off dyno that has a short log, just running migrations, it's pretty easy to spot. It occurs twice: once on startup and again on shutdown.

**Comment by Kyle-Verhoog** [comment]
@al-the-x 🤔 I don't think the `DATADOG_TRACE_DISABLED` flag exists did you mean `DD_TRACE_ENABLED=false`? As of `v0.45` we also disabled the startup logs which could lead to this log message being output. What version are you seeing this on still?

For anyone else, please let us know if this is still an issue. As far as I can tell this should be resolved by now!

**Comment by bmwant** [comment]
@Kyle-Verhoog we are still having this issue while both
```
DATADOG_TRACE = {
    'ENABLED': False,
}
```
and

```
export DD_TRACE_ENABLED="false"
```
are in place.

**Comment by Kyle-Verhoog** [comment]
@bmwant what version of ddtrace are you seeing this with?

**Comment by bmwant** [comment]
@Kyle-Verhoog  We've updated code to look at the same variable
```
DATADOG_TRACE = {
    'TAGS': {'env': ENV_NAME},
    'ENABLED': env.bool('DD_TRACE_ENABLED', default=True)
}
```
as well as passed `DD_TRACE_ENABLED="false"` into the containers
+ upgraded library to `ddtrace = "^0.50.0"` and seems like the issue has been resolved.

**Comment by Kyle-Verhoog** [comment]
Thanks for following up @bmwant! I _think_ this issue is resolved now. 🙂 

@al-the-x please re-open it if you're still seeing it.
